// <auto-generated />
using System;
using Infnet.EasyMediaLibrary.ConsoleApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infnet.EasyMediaLibrary.ConsoleApp.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MediaLibraryDbContext))]
    [Migration("20250517041711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Midia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMidia")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Midias");

                    b.HasDiscriminator<string>("TipoMidia").HasValue("Midia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Filme", b =>
                {
                    b.HasBaseType("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Midia");

                    b.Property<string>("ClassificacaoIndicativa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Filme");
                });

            modelBuilder.Entity("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Musica", b =>
                {
                    b.HasBaseType("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Midia");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artista")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Musica");
                });

            modelBuilder.Entity("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Podcast", b =>
                {
                    b.HasBaseType("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Midia");

                    b.Property<string>("Apresentador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Convidados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Podcast");
                });

            modelBuilder.Entity("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Serie", b =>
                {
                    b.HasBaseType("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Midia");

                    b.Property<int>("EpisodiosPorTemporada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroTemporadas")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Serie");
                });

            modelBuilder.Entity("Infnet.EasyMediaLibrary.ConsoleApp.Domain.Entities.Midia", b =>
                {
                    b.OwnsOne("Infnet.EasyMediaLibrary.ConsoleApp.Domain.ValueObjects.Duracao", "Duracao", b1 =>
                        {
                            b1.Property<Guid>("MidiaId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Minutos")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DuracaoMinutos");

                            b1.HasKey("MidiaId");

                            b1.ToTable("Midias");

                            b1.WithOwner()
                                .HasForeignKey("MidiaId");
                        });

                    b.Navigation("Duracao")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
